// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBelKEsnytzkUBjkgOn9rBGbFzfwh2GrIY',
    appId: '1:831648100316:web:f1b48e1c16425081972919',
    messagingSenderId: '831648100316',
    projectId: 'reminders-5a4d1',
    authDomain: 'reminders-5a4d1.firebaseapp.com',
    storageBucket: 'reminders-5a4d1.firebasestorage.app',
    measurementId: 'G-PDV39XC5XY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX83OWKUBOSsL9ZqfxSQfie01RPZ-OMmQ',
    appId: '1:831648100316:android:a417ccd002ad97f5972919',
    messagingSenderId: '831648100316',
    projectId: 'reminders-5a4d1',
    storageBucket: 'reminders-5a4d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeiZ0EyNkSHGUaE2SAitxXzFrjERkF9lk',
    appId: '1:831648100316:ios:7847769cd8b725d8972919',
    messagingSenderId: '831648100316',
    projectId: 'reminders-5a4d1',
    storageBucket: 'reminders-5a4d1.firebasestorage.app',
    iosBundleId: 'com.example.reminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeiZ0EyNkSHGUaE2SAitxXzFrjERkF9lk',
    appId: '1:831648100316:ios:7847769cd8b725d8972919',
    messagingSenderId: '831648100316',
    projectId: 'reminders-5a4d1',
    storageBucket: 'reminders-5a4d1.firebasestorage.app',
    iosBundleId: 'com.example.reminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBelKEsnytzkUBjkgOn9rBGbFzfwh2GrIY',
    appId: '1:831648100316:web:f5678beb697a913b972919',
    messagingSenderId: '831648100316',
    projectId: 'reminders-5a4d1',
    authDomain: 'reminders-5a4d1.firebaseapp.com',
    storageBucket: 'reminders-5a4d1.firebasestorage.app',
    measurementId: 'G-HJSMHNNR7D',
  );
}
